### PR TITLE
Added hmd tracking etc.

### PR DESCRIPTION
**Pull request by xinaesthete**
As discussed in https://github.com/jovr/jogl-hello-vr/issues/1

### CODE REVIEW

**Comment by elect86** [comment]
Shit, I didn't realize I had explicitely to accept  :pensive:

Anyway, we are again working at it starting from now (my collegue is working on the lib updating), do you have any updates in the meanwhile?

**Comment by xinaesthete** [comment]
Well, I got my other app working about right, although not quite at proper frame rate - I'll need to change the way JOGL drives the frames.  As you noticed, this pull request wasn't actually for a working version, good to see that you've apparently got it working now, I'll try to take a proper look at some point.

It was decided not to focus on VR for my other project for the time being (and in fact, it's likely that future VR incarnations will be a new JS codebase anyway)... so I'm not sure how much I'll really be using Java for VR stuff.  I might still have a go at making a version of WorldWind work with jopenvr; I'm hoping to make more time for map related stuff I want to play around with, although again it might end up being more on the JS side.  I already did some hacking of the Java version of WorldWind a while ago, so maybe I'll keep building on that.  It's a hobby project for me, but one that I hope to make time for.

**Comment by elect86** [comment]
Would you like to investigate together some ways to increase the frame rate?

I'd be available also to assist, as far as I can, with WorldWind..

**Comment by xinaesthete** [comment]
From my previous WorldWind hacking I think I know my way around it well enough to get it working in VR without too much effort once I get around to it; I had successfully got it rendering to various render targets from different perspectives, so should be similar again to get basic VR working, although a useable interface would be another story entirely and would involve more involved work.  It would be good to have the basic thing working out there as an example project, anyway.  I should be able to do that in a few weeks time.

As for the framerate thing: from my understanding of OpenVR, it should be `waitGetPoses` that blocks until the time when the driver is wanting another frame, so having anything like a JOGL `Animator` involved in the process is liable to cause some contention.  In my other app (using a slightly old version of JOGL, not that I believe that to be relevant), I tried configuring my animator to run as fast as possible but I think I still was locked at 60fps - would need to double check details.  I just had another quick look at your code, and see that you're also using `Animator` similarly.  You might try setting that flag and see how it goes.

So anyway, the internal workings of `Animator` are what we need to investigate, considering implementing a new version more tailored for the needs of VR.

**Comment by xinaesthete** [comment]
Oh yeah, my app was using old-style `GLCanvas`, it might be that with the NEWT style things are better.  That was on my todos.

**Comment by xinaesthete** [comment]
Another OpenVR thing I'd like to try making, that could make a good fairly basic sample project and a handy utility, is a clock overlay.  Not sure if such a thing already exists.

**Comment by elect86** [comment]
The only lag problem I had was when I was rotating my head left and right fast and I could see small jumps... I turned off v-sync and it worked as a charm.. you may want to check that.

Also set `animator.setExclusiveContext(true);`

All my tests so far were on newt

Clock overlay? Do you mean like watching somewhere a clock in vr?

**Comment by xinaesthete** [comment]
ok, useful suggestions, thanks.

For the clock overlay, yes, I mean something so that you can glance at the time easily when using arbitrary VR stuff.  Loss of connection with outside world can be a problem!

**Comment by elect86** [comment]
:D

yep, it should be pretty feasible, I'd render the background on a texture and then the two sticks (for hours and minutes) on top

**Comment by xinaesthete** [comment]
JOGL also has some useful text rendering stuff.

**Comment by sjpt** [comment]
I just tried elect86's suggestion and turned v-sync off and it worked a treat; the framerate went to 90fps rather than 60fps.  Thankyou.

Working with xinaesthete; same application, we'd been busy on other things hence the gap.
Still using GLCanvas for now.
Works OK using FPSAnimator set to 90fps, or regular Animator with setRunAsFastAsPossible(true)

Setting v-sync off is a bit of an issue as the way Nvidia control panel works it will apply to ALL java apps.  Is there a good way to do it from within the app itself?

**Pull request merged**
